[Solved] PRG_요걱 시스템 [Solved] PRG_문자열 마음대로 정렬하기
Kernel360-4cell/algorithm-study pull request #24
Opened 2023-11-30 02:10 UTC by ShineCorine

## 문제 및 풀이과정

[문자열 마음대로 정렬하기](https://school.programmers.co.kr/learn/courses/30/lessons/12915)
소요 시간 : 30분
- 문자열 정렬 기준을 정하는 문제였던 것 같습니다.
- 처음에는 서브스트링만으로 정렬하니 당연히 틀렸습니다.
- 문제를 다시 보니 "[n] 번째 문자열이 같으면 사전순으로 정렬하라" 라는 말을 대충 듣고 반영을 하지 않아 생긴 문제였습니다.
- 문제를 자세히 읽어야하겠다는 생각이 들었습니다(항상 이 점이 문제같습니다.)

## 문제 및 풀이 과정
[요격 시스템](https://school.programmers.co.kr/learn/courses/30/lessons/181188
소요 시간 : 10분
- 괜히 시간 더 들여서 따로 객체를 구성하지 않고 
- 여러분들 소스코드 참고해서 어제 제가 생각했던 풀이 방법을 재연해봤습니다.
- 제 풀이법도 프로그래머스 통과하는 데는 문제가 없었습니다만, 여러분들 풀이가 더 이해하기 쉽고 깔끔했던 것 같습니다. 
- 
## 궁금한 점

2023-12-01 08:00 UTC, kkkapuq requested changes
화, 수 문제 잘 봤습니다.
수요일 문제는 생각보다 엄청 간단하게 푸셨네요.. 자바로 겁나 복잡하게 풀었는데 ㅠㅠ

목 금 문제도 PR에 풀이과정 내용 첨부 부탁드립니다.

2023-12-01 08:11 UTC, kkkapuq requested changes

2023-12-01 08:11 UTC, kkkapuq commented on Week 4/PRG_레벨1_문자열 내 마음대로 저장하기/Jongmin_solved.java
> +                    return (s1.substring(n)).compareTo(s2.substring(n));
궁금한게.. 이게 substring(n)으로 자르는 이유가 있나요?
그냥 s1.charAt(n).compareTo(s2.charAt(n)) 으로 해도 될거같아서요

2023-12-01 08:14 UTC, kkkapuq commented
추가로 PR제목에 PRG_레벨2_요격 시스템 형태로 난이도 추가해주세요.
PR컨벤션 지켜주시면 감사하겠습니다.

2023-12-01 08:20 UTC, ShineCorine commented on Week 4/PRG_레벨2_요격 시스템/Jongmin_solved.java
> +        Arrays.sort(targets, (t1, t2)-> (t1[0]-t2[0]));
대신에 계속 시작점과 갱신해서 그게 역전되는 부분에서 해야해서, 굳이 앞에 있는 포격으로 최대한 많이 맞혀야 하는게 아니면, 형준님이 푸신 방법이 더 이해하기 쉽고 간단한 것 같았어요.

2023-12-01 08:22 UTC, ShineCorine commented on Week 4/PRG_레벨1_문자열 내 마음대로 저장하기/Jongmin_solved.java
> +                    return (s1.substring(n)).compareTo(s2.substring(n));
아 그러네요. 그런데 제가 처음에 생각한 풀이는 "n 번째 이후로  사전순 정렬" 이라서 이렇게 했던 것 같아요. 문제 의도에는 말씀하신대로 s1.charAt(n) 이 맞는 거 같아요.
근데 char도 compareTo 같은거 쓸 수 있나요?

2023-12-03 13:56 UTC, kkkapuq approved these changes
이번주도 고생하셨습니다.
휴식주라 저도 좀 해이해졌던 것 같은데.. 반성하고 다시 열심히 해보도록 하겠읍니다..

2023-12-03 13:56 UTC, kkkapuq commented on Week 4/PRG_레벨2_광물 캐기/Jongmin_solve.java
> +                valueToAdd = 36;
나머지는 다 이해가 됐는데, 이게 왜 36으로 정해진건지 이해가 안됩니다.
돌 기준으로 환산하신거같은데 25여야 되는거아닌가여?

2023-12-03 13:56 UTC, kkkapuq commented on Week 4/PRG_레벨2_H-Index/Jongmin_Solved.java
> +        for (int i = citations.length - 1; i >= 0; i--) {
좋은 접근인것 같습니다.
코테에선 필요한 메서드가 뭔지 모를수도있으니.. 이렇게 내림차순으로 정렬을 어떻게 해야하는지 모르는 경우는 이런식으로 접근하면 풀이가 가능하겠네요.

참고로 자바 배열 내림차순은
`Arrays.sort(citations, Collections.reverseOrder())` 해주시면 되니, 외워두시면 좋습니다.
매개변수로 뒤에 하나 추가해주면 돼요

2023-12-03 14:19 UTC, ShineCorine commented
> 추가로 PR제목에 PRG_레벨2_요격 시스템 형태로 난이도 추가해주세요. PR컨벤션 지켜주시면 감사하겠습니다.
네!

2023-12-04 00:35 UTC, anso33 approved these changes
종민님은 항상 열심히 고민하시고 코드를 작성하시는 것 같아요 물론 형준님도지만!!! ㅋㅋㅋ 자세를 배워야겠습니다.... 굳굳!!

2023-12-04 00:35 UTC, anso33 commented on Week 4/PRG_레벨2_광물 캐기/Jongmin_solve.java
> +                valueToAdd = 36;
222......

2023-12-04 00:43 UTC, anso33 approved these changes
도와주쎼요

2023-12-04 00:47 UTC, ShineCorine commented on Week 4/PRG_레벨2_H-Index/Jongmin_Solved.java
> +        for (int i = citations.length - 1; i >= 0; i--) {
네! 자바에서 익숙하지 않악서 외워야 할게 많은 것 같아요. 실제 상황에서 긴장해서 문법때문에 못풀면 정말 아쉬울 것 같아요. 감사합니다!

2023-12-04 01:03 UTC, ShineCorine commented on Week 4/PRG_레벨2_광물 캐기/Jongmin_solve.java
제가 하드코딩으로 숫자를 의미없게 쓰고 주석을 소홀히해서 어렵게 쓴 것 같습니다. 잘못했습니다...
저는 5개묶음을 한 자루로 설정하고 다이아, 철, 돌의 숫자를 각각 6진법 숫자에 담았습니다. 
(6진법인 이유는 5진법은 돌 5개가 철 한개와 구분이 안되기 때문입니다., 사실6진법 이상이면 다 되기 떄문에 10진법으로 해도 상관없습니다)
예를 들어서 $131_6$이면 다이아 한개, 철 3개, 돌 1개가 될텐데 이 정보를 담기 위해서는 $$(1\times6^2+3\times6+1)=131_6$$이 되고 여기서 값을 가져올 때는 다이아 개수는 $\div6^2$로 나눈 몫이 되고 철의 개수는 다이아를 뺀 나머지에서 $\div6$을 하고 그 나머지는 돌이 되는 식으로 값을 얻었습니다.
10진법에서 100의 자리 숫자를 얻기 위해서 $\div100$을 하고 몫을 취하는 것에서 힌트를 얻었습니다. 
배열로 하거나 패키지를 하나의 클래스로 만들었으면 훨씬 간단한데 배열을 잘 다루지 못하다보니 익숙한 일차원 배열 하나의 데이터에 여러 정보를 욱여넣다보니 다소 이해하기 어려운 코드가 된 것 같습니다.

2023-12-04 01:29 UTC, merged